import {
  mountainsImgMob,
  architecturalsImgMob,
  behindTheWavesMob,
  calmWatersImgMob,
  cityscapesImgMob,
  darkForestImgMob,
  daysVoyageImgMob,
  kingOnAfricaImgMob,
  landOfDreamsImgMob,
  milkywayImgMob,
  rageOfTheSeaImgMob,
  runningFreeImgMob,
  somwarpetImgMob,
  tripToNowhereImgMob,
  unforeseenCornersImgMob,
  worldTourImgMob,
} from "../../public/assets/stories/mobile";
import {
  mountainsImgDesk,
  architecturalsImgDesk,
  behindTheWavesDesk,
  calmWatersImgDesk,
  cityscapesImgDesk,
  darkForestImgDesk,
  daysVoyageImgDesk,
  kingOnAfricaImgDesk,
  landOfDreamsImgDesk,
  milkywayImgDesk,
  rageOfTheSeaImgDesk,
  runningFreeImgDesk,
  somwarpetImgDesk,
  tripToNowhereImgDesk,
  unforeseenCornersImgDesk,
  worldTourImgDesk,
} from "../../public/assets/stories/desktop";

const galleryData = [
  {
    id: 1,
    title: "The Mountains",
    author: "John Appleseed",
    imgSrcMobile: mountainsImgMob,
    imgSrcDesktop: mountainsImgDesk,
    hrefSrc: "#",
  },
  {
    id: 2,
    title: "Sunset Cityscapes",
    author: "Benjamin Cruz",
    imgSrcMobile: cityscapesImgMob,
    imgSrcDesktop: cityscapesImgDesk,
    hrefSrc: "#",
  },
  {
    id: 3,
    title: "18 Days Voyage",
    author: "Alexei Borodin",
    imgSrcMobile: daysVoyageImgMob,
    imgSrcDesktop: daysVoyageImgDesk,
    hrefSrc: "#",
  },
  {
    id: 4,
    title: "Architecturals",
    author: "Samantha Brooke",
    imgSrcMobile: architecturalsImgMob,
    imgSrcDesktop: architecturalsImgDesk,
    hrefSrc: "#",
  },
  {
    id: 5,
    title: "World Tour 2019",
    author: "Timothy Wagner",
    imgSrcMobile: worldTourImgMob,
    imgSrcDesktop: worldTourImgDesk,
    hrefSrc: "#",
  },
  {
    id: 6,
    title: "Unforeseen Corners",
    author: "William Malcolm",
    imgSrcMobile: unforeseenCornersImgMob,
    imgSrcDesktop: unforeseenCornersImgDesk,
    hrefSrc: "#",
  },
  {
    id: 7,
    title: "King on Africa: Part II",
    author: "Tim Hillenburg",
    imgSrcMobile: kingOnAfricaImgMob,
    imgSrcDesktop: kingOnAfricaImgDesk,
    hrefSrc: "#",
  },
  {
    id: 8,
    title: "The Trip to Nowhere",
    author: "Felicia Rourke",
    imgSrcMobile: tripToNowhereImgMob,
    imgSrcDesktop: tripToNowhereImgDesk,
    hrefSrc: "#",
  },
  {
    id: 9,
    title: "Rage of The Sea",
    author: "Mohammed Abdul",
    imgSrcMobile: rageOfTheSeaImgMob,
    imgSrcDesktop: rageOfTheSeaImgDesk,
    hrefSrc: "#",
  },
  {
    id: 10,
    title: "Running Free",
    author: "Michelle",
    imgSrcMobile: runningFreeImgMob,
    imgSrcDesktop: runningFreeImgDesk,
    hrefSrc: "#",
  },
  {
    id: 11,
    title: "Behind the Waves",
    author: "Lamarr Wilson",
    imgSrcMobile: behindTheWavesMob,
    imgSrcDesktop: behindTheWavesDesk,
    hrefSrc: "#",
  },
  {
    id: 12,
    title: "Calm Waters",
    author: "Samantha Brooke",
    imgSrcMobile: calmWatersImgMob,
    imgSrcDesktop: calmWatersImgDesk,
    hrefSrc: "#",
  },
  {
    id: 13,
    title: "The Milky Way",
    author: "Benjamin Cruz",
    imgSrcMobile: milkywayImgMob,
    imgSrcDesktop: milkywayImgDesk,
    hrefSrc: "#",
  },
  {
    id: 14,
    title: "Night at The Dark Forest",
    author: "Mohammed Abdul",
    imgSrcMobile: darkForestImgMob,
    imgSrcDesktop: darkForestImgDesk,
    hrefSrc: "#",
  },
  {
    id: 15,
    title: "Somwarpet’s Beauty",
    author: "Michelle",
    imgSrcMobile: somwarpetImgMob,
    imgSrcDesktop: somwarpetImgDesk,
    hrefSrc: "#",
  },
  {
    id: 16,
    title: "Land of Dreams",
    author: "William Malcolm",
    imgSrcMobile: landOfDreamsImgMob,
    imgSrcDesktop: landOfDreamsImgDesk,
    hrefSrc: "#",
  },
];

export default galleryData;
